<?xml version="1.0" encoding="utf-8"?><Database Name="QLTTN" Class="DoAnDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-D9DP6MT;Initial Catalog=QLTTN;Integrated Security=True" SettingsObjectName="DoAn.Properties.Settings" SettingsPropertyName="QLTTNConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.chiTietBaiThi" Member="chiTietBaiThis">
    <Type Name="chiTietBaiThi">
      <Column Name="maHs" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKythi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maCauHoi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dung_Sai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="cauHoi_chiTietBaiThi" Member="cauHoi" ThisKey="maCauHoi" OtherKey="ma" Type="cauHoi" IsForeignKey="true" />
      <Association Name="deThi_chiTietBaiThi" Member="deThi" ThisKey="maDe" OtherKey="ma" Type="deThi" IsForeignKey="true" />
      <Association Name="hocSinh_chiTietBaiThi" Member="hocSinh" ThisKey="maHs" OtherKey="ma" Type="hocSinh" IsForeignKey="true" />
      <Association Name="kyThi_chiTietBaiThi" Member="kyThi" ThisKey="maKythi" OtherKey="ma" Type="kyThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.cauHoi" Member="cauHois">
    <Type Name="cauHoi">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="goiY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="doKho" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="loaiCauHoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="cauHoi_chiTietBaiThi" Member="chiTietBaiThis" ThisKey="ma" OtherKey="maCauHoi" Type="chiTietBaiThi" />
      <Association Name="cauHoi_chiTietDethi" Member="chiTietDethis" ThisKey="ma" OtherKey="maCauHoi" Type="chiTietDethi" />
      <Association Name="cauHoi_dapAnCauhoi" Member="dapAnCauhoi" ThisKey="ma" OtherKey="maCauHoi" Type="dapAnCauhoi" Cardinality="One" />
      <Association Name="cauHoi_tinhTrangBaiLam" Member="tinhTrangBaiLams" ThisKey="ma" OtherKey="maCauHoi" Type="tinhTrangBaiLam" />
    </Type>
  </Table>
  <Table Name="dbo.chiTietDethi" Member="chiTietDethis">
    <Type Name="chiTietDethi">
      <Column Name="maDethi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maCauHoi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="cauHoi_chiTietDethi" Member="cauHoi" ThisKey="maCauHoi" OtherKey="ma" Type="cauHoi" IsForeignKey="true" />
      <Association Name="deThi_chiTietDethi" Member="deThi" ThisKey="maDethi" OtherKey="ma" Type="deThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dapAnCauhoi" Member="dapAnCauhois">
    <Type Name="dapAnCauhoi">
      <Column Name="maCauHoi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dapAn1" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="dapAn2" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="dapAn3" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="dapAn4" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="dapAn5" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="dapAn6" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="LaDapAnDung1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaDapAnDung2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaDapAnDung3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaDapAnDung4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaDapAnDung5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaDapAnDung6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="cauHoi_dapAnCauhoi" Member="cauHoi" ThisKey="maCauHoi" OtherKey="ma" Type="cauHoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.deThi" Member="deThis">
    <Type Name="deThi">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="slCauHoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoiGianLamBai_phut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="deThi_chiTietBaiThi" Member="chiTietBaiThis" ThisKey="ma" OtherKey="maDe" Type="chiTietBaiThi" />
      <Association Name="deThi_chiTietDethi" Member="chiTietDethis" ThisKey="ma" OtherKey="maDethi" Type="chiTietDethi" />
      <Association Name="deThi_thamGiaKyThi" Member="thamGiaKyThis" ThisKey="ma" OtherKey="maDe" Type="thamGiaKyThi" />
      <Association Name="deThi_tinhTrangBaiLam" Member="tinhTrangBaiLams" ThisKey="ma" OtherKey="maDe" Type="tinhTrangBaiLam" />
    </Type>
  </Table>
  <Table Name="dbo.giaoVien" Member="giaoViens">
    <Type Name="giaoVien">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NguoiDung_giaoVien" Member="NguoiDung" ThisKey="ma" OtherKey="manguoidung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.hocSinh" Member="hocSinhs">
    <Type Name="hocSinh">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="hocSinh_chiTietBaiThi" Member="chiTietBaiThis" ThisKey="ma" OtherKey="maHs" Type="chiTietBaiThi" />
      <Association Name="hocSinh_thamGiaKyThi" Member="thamGiaKyThis" ThisKey="ma" OtherKey="maHs" Type="thamGiaKyThi" />
      <Association Name="hocSinh_tinhTrangBaiLam" Member="tinhTrangBaiLams" ThisKey="ma" OtherKey="maHs" Type="tinhTrangBaiLam" />
      <Association Name="NguoiDung_hocSinh" Member="NguoiDung" ThisKey="ma" OtherKey="manguoidung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="manguoidung" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NguoiDung_giaoVien" Member="giaoVien" ThisKey="manguoidung" OtherKey="ma" Type="giaoVien" Cardinality="One" />
      <Association Name="NguoiDung_hocSinh" Member="hocSinh" ThisKey="manguoidung" OtherKey="ma" Type="hocSinh" Cardinality="One" />
      <Association Name="NguoiDung_taiKhoan" Member="taiKhoans" ThisKey="manguoidung" OtherKey="idNguoiSoHuu" Type="taiKhoan" />
      <Association Name="NguoiDung_adminn" Member="adminn" ThisKey="manguoidung" OtherKey="ma" Type="adminn" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.taiKhoan" Member="taiKhoans">
    <Type Name="taiKhoan">
      <Column Name="username" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[_password]" Member="_password" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idNguoiSoHuu" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NguoiDung_taiKhoan" Member="NguoiDung" ThisKey="idNguoiSoHuu" OtherKey="manguoidung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.thamGiaKyThi" Member="thamGiaKyThis">
    <Type Name="thamGiaKyThi">
      <Column Name="maHs" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKyThi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="deThi_thamGiaKyThi" Member="deThi" ThisKey="maDe" OtherKey="ma" Type="deThi" IsForeignKey="true" />
      <Association Name="hocSinh_thamGiaKyThi" Member="hocSinh" ThisKey="maHs" OtherKey="ma" Type="hocSinh" IsForeignKey="true" />
      <Association Name="kyThi_thamGiaKyThi" Member="kyThi" ThisKey="maKyThi" OtherKey="ma" Type="kyThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tinhTrangBaiLam" Member="tinhTrangBaiLams">
    <Type Name="tinhTrangBaiLam">
      <Column Name="maHs" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDe" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKythi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maCauHoi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="diem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoiGianUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cautraloi1" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cautraloi2" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cautraloi3" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cautraloi4" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cautraloi5" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cautraloi6" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="cauHoi_tinhTrangBaiLam" Member="cauHoi" ThisKey="maCauHoi" OtherKey="ma" Type="cauHoi" IsForeignKey="true" />
      <Association Name="deThi_tinhTrangBaiLam" Member="deThi" ThisKey="maDe" OtherKey="ma" Type="deThi" IsForeignKey="true" />
      <Association Name="hocSinh_tinhTrangBaiLam" Member="hocSinh" ThisKey="maHs" OtherKey="ma" Type="hocSinh" IsForeignKey="true" />
      <Association Name="kyThi_tinhTrangBaiLam" Member="kyThi" ThisKey="maKythi" OtherKey="ma" Type="kyThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.adminn" Member="adminns">
    <Type Name="adminn">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NguoiDung_adminn" Member="NguoiDung" ThisKey="ma" OtherKey="manguoidung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.kyThi" Member="kyThis">
    <Type Name="kyThi">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="maLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="kyThi_chiTietBaiThi" Member="chiTietBaiThis" ThisKey="ma" OtherKey="maKythi" Type="chiTietBaiThi" />
      <Association Name="kyThi_thamGiaKyThi" Member="thamGiaKyThis" ThisKey="ma" OtherKey="maKyThi" Type="thamGiaKyThi" />
      <Association Name="kyThi_tinhTrangBaiLam" Member="tinhTrangBaiLams" ThisKey="ma" OtherKey="maKythi" Type="tinhTrangBaiLam" />
    </Type>
  </Table>
</Database>