<?xml version="1.0" encoding="utf-8"?><Database Name="QLTTN" Class="DoAnDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-D9DP6MT;Initial Catalog=QLTTN;Integrated Security=True" SettingsObjectName="DoAn.Properties.Settings" SettingsPropertyName="QLTTNConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.adminn" Member="adminns">
    <Type Name="adminn">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NguoiDung_adminn" Member="NguoiDung" ThisKey="ma" OtherKey="manguoidung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.hocSinh" Member="hocSinhs">
    <Type Name="hocSinh">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maLop" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NguoiDung_hocSinh" Member="NguoiDung" ThisKey="ma" OtherKey="manguoidung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.giaoVien" Member="giaoViens">
    <Type Name="giaoVien">
      <Column Name="ma" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NguoiDung_giaoVien" Member="NguoiDung" ThisKey="ma" OtherKey="manguoidung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.taiKhoan" Member="taiKhoans">
    <Type Name="taiKhoan">
      <Column Name="username" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[_password]" Member="_password" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idNguoiSoHuu" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NguoiDung_taiKhoan" Member="NguoiDung" ThisKey="idNguoiSoHuu" OtherKey="manguoidung" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="manguoidung" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NguoiDung_adminn" Member="adminn" ThisKey="manguoidung" OtherKey="ma" Type="adminn" Cardinality="One" />
      <Association Name="NguoiDung_hocSinh" Member="hocSinh" ThisKey="manguoidung" OtherKey="ma" Type="hocSinh" Cardinality="One" />
      <Association Name="NguoiDung_giaoVien" Member="giaoVien" ThisKey="manguoidung" OtherKey="ma" Type="giaoVien" Cardinality="One" />
      <Association Name="NguoiDung_taiKhoan" Member="taiKhoans" ThisKey="manguoidung" OtherKey="idNguoiSoHuu" Type="taiKhoan" />
    </Type>
  </Table>
</Database>